version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'ezeelive-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'ezee-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ezeelive123
      MYSQL_DATABASE: ezeelive
      MYSQL_USER: ezeelive
      MYSQL_PASSWORD: ezeelive
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'ezeelive-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '80:80'
    volumes: 
      - /sessions
  redis:
    container_name: 'ezeelive-redis'
    image: redis:latest
    ports:
      - "6379:6379"